/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProgressRouteImport } from './routes/progress'
import { Route as HelloRouteImport } from './routes/hello'
import { Route as DebugRouteImport } from './routes/debug'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StorageSplatRouteImport } from './routes/storage.$'

const ProgressRoute = ProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => rootRouteImport,
} as any)
const HelloRoute = HelloRouteImport.update({
  id: '/hello',
  path: '/hello',
  getParentRoute: () => rootRouteImport,
} as any)
const DebugRoute = DebugRouteImport.update({
  id: '/debug',
  path: '/debug',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StorageSplatRoute = StorageSplatRouteImport.update({
  id: '/storage/$',
  path: '/storage/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/debug': typeof DebugRoute
  '/hello': typeof HelloRoute
  '/progress': typeof ProgressRoute
  '/storage/$': typeof StorageSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/debug': typeof DebugRoute
  '/hello': typeof HelloRoute
  '/progress': typeof ProgressRoute
  '/storage/$': typeof StorageSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/debug': typeof DebugRoute
  '/hello': typeof HelloRoute
  '/progress': typeof ProgressRoute
  '/storage/$': typeof StorageSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/debug' | '/hello' | '/progress' | '/storage/$'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/debug' | '/hello' | '/progress' | '/storage/$'
  id: '__root__' | '/' | '/debug' | '/hello' | '/progress' | '/storage/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DebugRoute: typeof DebugRoute
  HelloRoute: typeof HelloRoute
  ProgressRoute: typeof ProgressRoute
  StorageSplatRoute: typeof StorageSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/progress': {
      id: '/progress'
      path: '/progress'
      fullPath: '/progress'
      preLoaderRoute: typeof ProgressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hello': {
      id: '/hello'
      path: '/hello'
      fullPath: '/hello'
      preLoaderRoute: typeof HelloRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/debug': {
      id: '/debug'
      path: '/debug'
      fullPath: '/debug'
      preLoaderRoute: typeof DebugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/storage/$': {
      id: '/storage/$'
      path: '/storage/$'
      fullPath: '/storage/$'
      preLoaderRoute: typeof StorageSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DebugRoute: DebugRoute,
  HelloRoute: HelloRoute,
  ProgressRoute: ProgressRoute,
  StorageSplatRoute: StorageSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
