// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mlyowmvrpjtqruramrhp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1seW93bXZycGp0cXJ1cmFtcmhwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzY1NTEwNjEsImV4cCI6MjA5MjEyNzA2MX0.AdlYc8kU0HfymnHU4-ASXr-rpjf-O32Kynl3nUDy5VA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: typeof window !== "undefined" ? window.localStorage : undefined,
    persistSession: true,
    autoRefreshToken: true,
  }
});