// This file is automatically generated. Do not edit it directly.
// Server-side Supabase client with service role key - bypasses RLS.
// Use this for admin operations in server functions and server routes only.
// For user-authenticated queries (with RLS), use the auth middleware instead.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";

function createSupabaseAdminClient() {
  const env = (typeof process !== 'undefined' ? process.env : {}) as any;
  const g = (globalThis as any);

  const url = env.SUPABASE_URL || import.meta.env.VITE_SUPABASE_URL || g.SUPABASE_URL || g.VITE_SUPABASE_URL;
  const key = env.SUPABASE_SERVICE_ROLE_KEY || g.SUPABASE_SERVICE_ROLE_KEY;

  if (!url || !key) {
    if (typeof window === "undefined") {
      console.warn("Supabase Admin credentials missing from server environment.");
    }
    return null;
  }

  return createClient<Database>(url, key, {
    auth: {
      storage: undefined,
      persistSession: false,
      autoRefreshToken: false,
    },
  });
}

let _supabaseAdmin: ReturnType<typeof createSupabaseAdminClient> | undefined;

// Server-side Supabase client with service role - bypasses RLS
// SECURITY: Only use this for trusted server-side operations, never expose to client code
// Import like: import { supabaseAdmin } from "@/integrations/supabase/client.server";
export const supabaseAdmin = new Proxy({} as ReturnType<typeof createSupabaseAdminClient>, {
  get(_, prop, receiver) {
    if (!_supabaseAdmin) _supabaseAdmin = createSupabaseAdminClient() || undefined;
    if (!_supabaseAdmin) {
      if (typeof window === "undefined") {
        console.error(`Attempted to access supabaseAdmin.${String(prop)} but client is not initialized.`);
      }
      // Return a safe dummy for common Supabase methods
      if (prop === "from") return () => ({ select: () => ({ order: () => Promise.resolve({ data: [], error: new Error("Supabase Admin not initialized") }) }) });
      return () => { 
        console.error("Supabase Admin not initialized. Operation cancelled.");
        return Promise.resolve({ data: null, error: new Error("Supabase Admin not initialized") });
      };
    }
    return Reflect.get(_supabaseAdmin, prop, receiver);
  },
});
